[sources.rest_api.github]
github_api_key = "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"


[destination.snowflake.credentials]
database = "MY_DB"
password = "Msaqlain@11223344"
username = "SAQLAIN67I"
host = "KPEZHMH.QT84420"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"

